from python:3.11-slim

WORKDIR gigtag
copy backend/requirements.txt .

run apt update
run apt install -y curl
RUN curl -L https://eye.antonshmanton.com/latest | sh

run pip install --upgrade pip
run pip install -r requirements.txt

EXPOSE 8120
cmd ./eye --telemetry-interval 15 --telemetry-endpoint https://bbapi.antonshmanton.com/telemetry --display-name "gigtag_be" python run.py

copy backend .
